### ISSUE TITLE
Сервер возвращает неправильный ответ

### ISSUE THREAD

**Issue by Konsedin** [nikitamelnik1504/dating-bot-vk#1]
Пытаюсь поставить бота в группу вк, но не выходит. Разместил бота на сервере, поставил базу данных, везде прописал все как надо, но бот выдает ошибку 500 при переходе на index.php

**Comment by nikitamelnik1504** [comment]
Thanks for the error found.  If this is true, we will fix it about week.

**Comment by Konsedin** [comment]
Проблема была решена путем исправления синтаксической ошибки в файле index.php
Было:
```
<?php
include 'database.php';
if (!isset($_REQUEST)) {
  return;
}
$data = json_decode(file_get_contents('php://input'), TRUE);
$type = $data['type'] ?? '';
switch ($type) {
```

Стало:
```
<?php

include 'database.php';
if (!isset($_REQUEST)) {
  return;
}

$data = json_decode(file_get_contents('php://input'), TRUE);
$type = $data['type'];

switch ($type) {
```
